name: Symfony CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  symfony:
    name: Symfony 5.2 (PHP 8.0)

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      # Setup Github actions
      # https://github.com/actions/checkout (official)
      - name: Checkout
        uses: actions/checkout@v2

      # Setup PHP
      # https://github.com/shivammathur/setup-php (community)
      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: ctype, dom, filter, gd, iconv, intl, json, mbstring, pdo, pdo_mysql, xml
        env:
          update: true

      - name: Check PHP Version
        run: php -v

      # Install Composer
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Project
        run: ./entrypoint.sh install env=prod

      - name: Check for code quality errors
        run: ./entrypoint.sh lint_sniff

      - name: Run Unit tests
        run: ./entrypoint.sh unit_tests

      - name: Run Integration tests
        run: ./entrypoint.sh integration_tests
