name: Make CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install Ubuntu dependencies with sudo apt install -y
      run: sudo apt install -y gawk make

    - name: Check for basic execution
      run: make && make generate

  macos:
    runs-on: macos-latest
    if: "contains(toJSON(github.event.commits.*.message), '[macos]')"

    steps:
    - uses: actions/checkout@v2

    - name: install MacOS dependencies with brew install
      run: brew install gawk make

    - name: Check for basic execution
      run: make && make generate
